/**
 * emit.mjs - writes the neutral model (model.mjs) in the editor's own format.
 * Format checked against the editor's docs on 2026-09-29:
 *   Sveltia    - sveltiacms.app/en/docs (start, fields, fields/select, fields/number, collections/entries/slugs)
 * and, for the kinds added 2026-09-30 (each page read that day, as its .md source):
 *   image      - sveltiacms.app/en/docs/fields/image, fields/file (media_folder, public_folder,
 *                choose_url, field-level media_libraries), media/internal (field-level folders),
 *                media (slugify_filename). A public path starting with "." is kept as written:
 *                Sveltia's source, src/lib/services/config/folders/assets.js, normalizeAssetFolder
 *                (sveltia/sveltia-cms commit 87bac25, 2026-09-29).
 *   date       - sveltiacms.app/en/docs/fields/datetime (type: date, input_timezone: utc)
 *   list       - sveltiacms.app/en/docs/fields/list (simple list, fields, root: true)
 *   relation   - sveltiacms.app/en/docs/fields/relation (collection, value_field {{slug}},
 *                display_fields, search_fields, multiple, min)
 *   object     - sveltiacms.app/en/docs/fields/object
 *   create/delete/duplicate - sveltiacms.app/en/docs/collections/entries/operations
 *   one-file collection - sveltiacms.app/en/docs/collections/files and fields/list "Top-Level List"
 *                (single-file entry collections are JSON-only: collections/entries/single-file)
 *   omit_empty_optional_fields - sveltiacms.app/en/docs/data-output and frameworks/astro
 * Measured live 2026-09-30 (Sveltia 0.223.0, all eight kinds on the studio's live walk site):
 *   - image: an upload lands in the media folder in the same commit as the entry;
 *     removing the image from an entry later does NOT delete the file - it stays in the repo.
 *   - omit_empty_optional_fields: empty optional fields leave the file on save (no ""),
 *     and so does an existing empty optional list: a list written as `[]` was dropped on the
 *     first save of an untouched entry. Booleans (true) were kept.
 *   - one-file collection: the save removed every YAML comment in the file, so cli.mjs
 *     refuses a commented data file (model.mjs yamlCommentLines).
 * Two traps this file exists to avoid: Sveltia treats every field as required
 * unless told otherwise, and its number field accepts whole numbers only
 * unless value_type is "float" - a price of 14.50 would be refused.
 */
/*
 * SVELTIA_VERSION and SVELTIA_INTEGRITY change together: the integrity value is
 * the hash of exactly that version's file. The /admin policy in headers.mjs
 * also scopes its script-src to this version's path.
 * To recompute after bumping the version (unpkg sends Access-Control-Allow-Origin: *):
 *   curl -sL https://unpkg.com/@sveltia/cms@<version>/dist/sveltia-cms.js | openssl dgst -sha384 -binary | openssl base64 -A
 * then write the result as "sha384-<output>".
 * Measured 2026-09-29 for 0.223.0 (2,181,501 bytes).
 */
export const SVELTIA_VERSION = "0.223.0"; // npm view @sveltia/cms version, 2026-09-29
export const SVELTIA_INTEGRITY =
  "sha384-kGBT9JIpQwruwT9A4VINu7Zmzw3Qttn/tO+EBFTddw1/PFUnt4074uXE9RNhX3N3";

export const HEADER =
  "# Generated by scripts/cms.mjs from src/content.config.ts and cms/fields.json.\n" +
  "# Do not edit by hand: run `npm run cms -- generate`.\n";

function sveltiaField(f) {
  const widget = {
    string: "string",
    text: "text",
    number: "number",
    integer: "number",
    boolean: "boolean",
    select: "select",
    image: "image",
    date: "datetime",
    datetime: "datetime",
    list: "list",
    objectList: "list",
    object: "object",
    relation: "relation",
  }[f.kind];
  const out = { name: f.name, label: f.label, widget, required: f.required };
  if (f.hint) out.hint = f.hint;
  if (f.default !== undefined) out.default = f.default;
  if (f.kind === "number")
    Object.assign(out, { value_type: "float", step: f.step });
  if (f.kind === "integer") out.value_type = "int";
  if (f.min !== undefined) out.min = f.min;
  if (f.kind === "select") {
    if (f.multiple) out.multiple = true;
    out.options = f.choices.map((c) => ({ label: c.label, value: c.value }));
  }
  if (f.kind === "image") {
    if (f.multiple) out.multiple = true;
    Object.assign(out, {
      media_folder: `/${f.mediaFolder}`,
      public_folder: f.publicFolder,
      // A pasted web address would not resolve through Astro's image().
      choose_url: false,
      media_libraries: { default: { config: { slugify_filename: true } } },
    });
  }
  // A date only, stored as YYYY-MM-DD, picked in UTC so the day cannot shift
  // with the editor's time zone (datetime docs: picker_utc / input_timezone).
  if (f.kind === "date") Object.assign(out, { type: "date", input_timezone: "utc" });
  if (f.kind === "datetime") out.input_timezone = "utc";
  if (f.kind === "relation") {
    if (f.multiple) out.multiple = true;
    // A field literally named "slug" must be written {{fields.slug}} (relation docs, value_field).
    const shown = f.displayField === "slug" ? "{{fields.slug}}" : f.displayField;
    Object.assign(out, {
      collection: f.collection,
      value_field: "{{slug}}",
      display_fields: [shown],
      search_fields: [shown],
    });
  }
  if (f.kind === "objectList" && f.summary) out.summary = f.summary;
  if (f.fields) out.fields = f.fields.map(sveltiaField);
  return out;
}

function operations(c) {
  const out = {};
  if (!c.delete) out.delete = false;
  // Duplicating makes a new entry too, so it follows create.
  if (!c.create) out.duplicate = false;
  return out;
}

function folderCollection(c) {
  return {
    name: c.name,
    label: c.label,
    folder: c.folder,
    create: c.create,
    ...operations(c),
    extension: "md",
    format: "frontmatter",
    identifier_field: c.slugField,
    slug: `{{fields.${c.slugField}}}`,
    fields: [
      ...c.fields.map(sveltiaField),
      ...(c.body
        ? [
            {
              name: "body",
              label: c.bodyLabel,
              widget: "markdown",
              required: false,
              ...(c.bodyHint ? { hint: c.bodyHint } : {}),
            },
          ]
        : []),
    ],
  };
}

/**
 * A collection loaded with Astro's file() loader: one YAML/JSON file holding a
 * list of rows, each with an id. Edited as one file whose only field is a
 * top-level list; create/delete become adding/removing rows.
 */
function fileCollection(c) {
  const list = {
    name: c.name,
    label: c.label,
    widget: "list",
    root: true,
    ...(c.summary ? { summary: c.summary } : {}),
    ...(c.create ? {} : { allow_add: false, allow_duplicate: false }),
    ...(c.delete ? {} : { allow_remove: false }),
    fields: [
      {
        name: "id",
        label: c.idLabel,
        widget: "string",
        required: true,
        ...(c.idHint ? { hint: c.idHint } : {}),
      },
      ...c.fields.map(sveltiaField),
    ],
  };
  return {
    name: c.name,
    label: c.label,
    files: [{ name: c.name, label: c.label, file: c.file, fields: [list] }],
  };
}

/**
 * A record (record.mjs): one JSON file holding one object, edited as one form.
 * Measured live 2026-09-30 (Sveltia 0.223.0, a hand-written config of this shape):
 * a nested object and a number saved, keys the form does not show were kept, an
 * emptied optional number was written as null. `format` on the file entry is read
 * before the collection's (Sveltia src/lib/services/contents/file/config.js, getFileConfig).
 */
function recordCollection(r) {
  return {
    name: r.name,
    label: r.label,
    ...(r.description ? { description: r.description } : {}),
    files: [{ name: r.name, label: r.label, file: r.file, format: "json", fields: r.fields.map(sveltiaField) }],
  };
}

export function sveltiaConfig(model, { repo, branch = "main", authUrl } = {}) {
  if (!repo || !/^[\w.-]+\/[\w.-]+$/.test(repo))
    throw new Error(
      "sveltia: --repo owner/name is required (the GitHub repository the site builds from).",
    );
  const backend = { name: "github", repo, branch };
  if (authUrl) backend.base_url = authUrl;
  return {
    backend,
    // ASCII file names: "Crème brûlée" becomes creme-brulee.md (Sveltia docs, collections/entries/slugs, read 2026-09-29).
    slug: { encoding: "ascii", clean_accents: true },
    media_folder: "public/images/uploads",
    public_folder: "/images/uploads",
    ...(model.omitEmpty ? { output: { omit_empty_optional_fields: true } } : {}),
    collections: [
      ...model.collections.map((c) => (c.file ? fileCollection(c) : folderCollection(c))),
      ...(model.records ?? []).map(recordCollection),
    ],
  };
}

export function sveltiaIndexHtml(version, integrity = SVELTIA_INTEGRITY) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="robots" content="noindex" />
    <title>Content editor</title>
  </head>
  <body>
    <script src="https://unpkg.com/@sveltia/cms@${version}/dist/sveltia-cms.js" integrity="${integrity}" crossorigin="anonymous"></script>
  </body>
</html>
`;
}
